# -*- coding: utf-8 -*-
{
    'name' : 'Dyanamic Report Clickable View',
    'version' : '13.1.0',
    'summary': " All Accounting Reports clickable View",
    'description': """ All Accounting Reports clickable View""",
    'category': 'Accounting/Accounting',
    'author': 'Juleb',
    'website': 'juleb.com',
    'depends': [
        'account',
        # 'accounting_pdf_reports',
    ],
    'data': [
         'security/ir.model.access.csv',
         'data/data_financial_report.xml',
         'views/views.xml',
         'views/res_company_view.xml',
         'views/general_ledger_view.xml',
         'views/partner_ledger_view.xml',
         'views/trial_balance_view.xml',
         'views/partner_ageing_view.xml',
         'views/financial_report_view.xml',
         'wizard/general_ledger_view.xml',
         'wizard/partner_ledger_view.xml',
         'wizard/trial_balance_view.xml',
         'wizard/partner_ageing_view.xml',
         'wizard/financial_report_view.xml',
     ],
    'license': 'AGPL-3',
    'qweb': ['static/src/xml/view.xml'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
