from . import student
from . import student_session
from . import student_attendance
from . import student_class
from . import res_partner
from . import crm
from . import account
from . import product
from . import brochure